# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: amelio_cp
channels:
- conda-forge # downaload packages from conda-forge (instead of pip)
dependencies:
- python=3.13
- numpy
- pandas
- scikit-learn=1.7.2
- scipy
# - skopt
- shap=0.46.0
- joblib
# - bayes-opt